### ISSUE TITLE
make train-nlu Problem !

### ISSUE THREAD

**Issue by m2cci-sba** [RasaHQ/starter-pack-rasa-nlu#14]
$ make train-nlu
python -m rasa_nlu.train -c nlu_config.yml --data data/nlu_data.md -o models --project current --verbose
C:\Users\sbaja\AppData\Local\Programs\Python\Python36\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
2019-05-18 11:23:49 INFO     rasa_nlu.utils.spacy_utils  - Trying to load spacy model with name 'en'
Traceback (most recent call last):
  File "C:\Users\sbaja\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\sbaja\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\sbaja\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_nlu\train.py", line 184, in <module>
    num_threads=cmdline_args.num_threads)
  File "C:\Users\sbaja\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_nlu\train.py", line 148, in do_train
    trainer = Trainer(cfg, component_builder)
  File "C:\Users\sbaja\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_nlu\model.py", line 155, in __init__
    self.pipeline = self._build_pipeline(cfg, component_builder)
  File "C:\Users\sbaja\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_nlu\model.py", line 166, in _build_pipeline
    component_name, cfg)
  File "C:\Users\sbaja\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_nlu\components.py", line 441, in create_component
    cfg)
  File "C:\Users\sbaja\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_nlu\registry.py", line 143, in create_component_by_name
    return component_clz.create(config)
  File "C:\Users\sbaja\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_nlu\utils\spacy_utils.py", line 73, in create
    nlp = spacy.load(spacy_model_name, parser=False)
  File "C:\Users\sbaja\AppData\Local\Programs\Python\Python36\lib\site-packages\spacy\__init__.py", line 15, in load
    return util.load_model(name, **overrides)
  File "C:\Users\sbaja\AppData\Local\Programs\Python\Python36\lib\site-packages\spacy\util.py", line 119, in load_model
    raise IOError(Errors.E050.format(name=name))
OSError: [E050] Can't find model 'en'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.
Makefile:24: recipe for target 'train-nlu' failed
make: *** [train-nlu] Error 1

**Comment by m2cci-sba** [comment]
I have tried the solutions proposed on closed issues but i'm getting the same error ? i need your help please?

**Comment by m2cci-sba** [comment]
@MetcalfeTom
